apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: multiapp-containers
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: multiapp
